### ISSUE TITLE
Feature Request: .active class on route match

### ISSUE THREAD

**Issue by kwhitley** [metonym/svelte-link#13]
A regular use-case for a generic `Link` component is simply to add an `.active` (most common) class for styling differences, indication of navigation, etc, rather than adding that logic to each link's implementation code.

If you added that automatic injection when a route prefix matches (for deep navigation) with an `exact` modifier to force a full path match, that would be awesome...

```js
<Link href="/about">About</Link>
<!-- when viewed at "/about/somewhere" should render: -->
<a href="/about" class="active">About</Link>

<Link href="/about" exact>About</Link>
<!-- when viewed at "/about/somewhere" should render: -->
<a href="/about">About</Link>
```

Just a suggestion!

**Comment by kwhitley** [comment]
Example from my own component (uses SvelteKit page store in my case), minus your component's other cool features:

```js
<script>
  import { page } from '$app/stores'
  export let href
  export let exact = false

  $: active = exact
              ? $page.url.pathname === href
              : $page.url.pathname.indexOf(href) === 0
</script>

<a href={href} class:active>
  <slot />
</a>
```

**Comment by metonym** [comment]
I like this suggestion of an `active` boolean prop. It can go further by setting `aria-current="page"` if `true`.

**Comment by metonym** [comment]
Supported in [v1.2.0](https://github.com/metonym/svelte-link/releases/tag/v1.2.0)
