### ISSUE TITLE
[feature] Default outbound to true if `href` points to an external url

### ISSUE THREAD

**Issue by madeleineostoja** [metonym/svelte-link#2]
Hey just a small feature request — it would be great if the default for `outbound` was a little smarter, and defaulted to `true` if `href` is an external URL, which the user can easily override with `outbound={false}` to force all links to be same-target.

This would be especially useful if you don't have control over the href, for example in content from a CMS, where you want external links to automatically be outbound.

Happy to submit a PR if you're open to it

**Comment by metonym** [comment]
That's a wonderful idea. Open to PRs

**Comment by madeleineostoja** [comment]
Done :)

**Comment by madeleineostoja** [comment]
Btw I was snooping how you did the typescript defs for `svelte-link`, and `sveld` looks amazing, it's exactly what I've been looking for. Did it generate the definitions for `svelte-link`, or did you hand write them? Curious if it would work with legit ts in svelte components (ie: `<script lang="ts">`)

**Comment by metonym** [comment]
Thanks – there's definitely no shortage of Svelte docgen libraries, but sveld has opinionated defaults and is designed to be easy to integrate while requiring little maintenance by the library author. The generated definitions uses the typed `SvelteComponent` interface available in Svelte >=v3.30.

For this repo, I ran `npx sveld`.

**Comment by metonym** [comment]
Published to NPM in [v1.0.0](https://github.com/metonym/svelte-link/releases/tag/v1.0.0)

**Comment by madeleineostoja** [comment]
Sorry just noticed a bug! Pushed to the fork, but the window check should actually be `typeof window !== 'undefined`), since doing a falsey check on `window` will still fail in SSR environments.

**Comment by madeleineostoja** [comment]
Made another PR, sorry! Should have caught it before merging the last one 🤦‍♀️

**Comment by metonym** [comment]
No problem – patched in v1.0.1
